# Site
repository: luiz-chagas/luiz-chagas.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Luiz Chagas
title: Programmer / Developer / Software Engineer
email: luiz@luizchagas.com
email_title: Luiz Chagas
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: functionalguy
github_username: luiz-chagas
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: luizchagas
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#  - title: Link name
#    icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#    url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/luiz.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi! I'm a software developer with a background in Computer Science and about 7 years of experience.

  I currently work with full stack development, mainly with <mark>JavaScript</mark> technologies.

  I'm very proficient with <mark>React</mark>, <mark>Typescript</mark>, <mark>Node.js</mark>, <mark>(No)Sql Databases</mark>, API integrations and other things.

  Most of my recent work revolves around building applications with great User Experience while keeping code quality to the best I can (readable, tested, self-documented and simple).

  <mark>Functional Programming</mark> is my jam.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Crema
        sub_title: Sr. Application Developer
        caption: December 2019 - present
        link: https://crema.us/
        quote: >
          Crema is digital product agency helping individuals and companies thrive through innovation, design and technology.
        description: | # this will include new lines to allow paragraphs
          Developed web and mobile applications. Built both enterprise application and public products. Mentored junior developers.

          Worked on a daily basis with JavaScript, Typescript, React, React-Native, Redux, Firebase, Expo, MaterialUI, NodeJS.
      - layout: left
        title: Crema
        sub_title: Application Developer
        caption: November 2018 - December 2019
        link: https://crema.us/
        quote: >
          Crema is digital product agency helping individuals and companies thrive through innovation, design and technology.
        description: | # this will include new lines to allow paragraphs
          Developed web and mobile applications. Built both enterprise application and public products.
      - layout: left
        title: Self-Employed
        sub_title: Software Developer
        caption: January 2017 - November 2018
        description: | # this will include new lines to allow paragraphs
          Developed full-stack web applications. For some reason, I worked on a lot of projects with real time interactions and optimization of existing software.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "Vera: Plant Care App"
        link: https://bloomscape.com/vera/
        quote: >
          Vera is care management app for plants that makes tracking as fun as the care itself, so anyone can be a successful plant parent.
        description: | # this will include new lines to allow paragraphs
          I worked on building Vera from scratch. We were a team of 4 people (1 designer, 2 devs, 1 marketing) and we built the first version of the app in only 16 days. 
          Vera was a hit on both App Store and Play Store reaching over 200k users in under a year. The application now belongs to Bloomscape.

          The main technologies used were <mark>React-Native</mark> and <mark>Google Firebase</mark>.
      - layout: left
        title: "Stock Info"
        link: https://github.com/luiz-chagas/stock-info
        github: luiz-chagas/stock-info
        description: | # this will include new lines to allow paragraphs
          I wrote my own roboadvisor to trade stocks using Robinhood. As a by-product I built `stock-info`, a utility that retrieves current stock information from Yahoo's Finance API.

          The library runs on node and is exported as an open source package on NPM, being used in over 50 projects on GitHub.
  - title: Education
    layout: list
    content:
      - layout: top
        title: Centro Federal de Educacao Tecnologica de Minas Gerais (CEFET-MG)
        caption: 2010 - 2016
        sub_title: Bachelor's Degree - Computer Engineering
      - layout: top
        title: Kansas State University
        caption: 2014 - 2015
        sub_title: Exchange Student - Computer Science
      - layout: top
        title: Centro Federal de Educacao Tecnologica de Minas Gerais (CEFET-MG)
        caption: 2007 - 2009
        sub_title: Associate's Degree - Information Science
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I love soccer, games (computer/board/etc), my family, grilling and beer. 🍻

      I also like to dig deep into programming and study topics of my interest, you may
      find me reading textbooks about Computer Science / Software Development. 

      I'm overall a friendly person and enjoy being nice to others.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  # - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
